export const backendServer = "https://aichathub.azurewebsites.net";
// export const backendServer = "http://localhost:3001";
export const GUEST_EMAIL = "guest@example.com";
export const GUEST_USERNAME = "guest";
export const AI_EMAIL = "ai@example.com";
export const AI_USERNAME = "ai";
export const GOOGLE_LOGIN_CLIENT_ID = "544615908375-24otdb6t0v54un3b1n2b57iflovhj9no.apps.googleusercontent.com";
export const GITHUB_LOGIN_CLIENT_ID = "dbc1cef903c0e90e1033";
export const LLAMA_70B_API = "https://welllitappropriatejavabytecode.aichathubapp.repl.co/api/llama70b";