name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install and deploy
        run: npm install --legacy-peer-deps && npm run deploy
