name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install and build
        run: npm install --legacy-peer-deps && npm run build
        env:
          CI: ""

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
